baseURL: https://example.com
title: Hugo
theme: izi-hugo-theme

# Default content language, support: en-gb (English), en-us (American English)
defaultContentLanguage: en-gb

# !!! exampleSite ONLY, DELETE THIS LINE FOR YOUR OWN USE: `themesDir: ../../`
themesDir: ../../

paginate: 3

# Hugo Configure Markup
# More info: https://gohugo.io/getting-started/configuration-markup#
markup:
  highlight:
    # but you can also be speciffic by specifying the language when opening the blog, for example: ```java
    guessSyntax: true
    # makes it use CSS clases so colours can be adapted with CSS, for example for dark themes
    noClasses: false
  # needed to render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
  goldmark:
    renderer:
      unsafe: true

# Social links in footer
# Simply delete the ones you don't have
# Source: https://github.com/simple-icons/simple-icons
social:
  github: your-github-link
  twitter: your-twitter-link
  stackoverflow: your-stackoverflow-link
  email: your-email
  facebook: your-facebook-link
  mastodon: your-mastodon-link
  linkedin: your-linkedin-link


# Site parameters
params:
  # Site Author name, showed at the top of the pages
  author: Author Name
  # Author biography, shown at the top of the pages
  bio: Your bio
  # Site Description, used in HTML meat
  description: My Blog

  favicon: 'image/favicon.svg'
  avatar: 'image/avatar.png'

  titleFont: 'https://fonts.googleapis.com/css?family=Unna'
  textFont: 'https://fonts.googleapis.com/css?family=Open+Sans'

  ###########################################
  # Optional Configuration
  ###########################################

  # To enable RSS, you could set `enableRSS: true`, default is `true`
  enableRSS: true
  # To hidden post summary in home page, you could set `hiddenPostSummaryInHomePage: true`, default is `false`
  hiddenPostSummaryInHomePage: false
  # Website copy write, default: '© Copyright {currentYear} ❤️ {params.author}'
  copyright: ''

  # You can put your custom css and js to `static` directory, or use remote css and js files which start with `http://` or `https://`
  customCSS:
    ## e.g.
    # - css/custom.css # local css in `static/css/custom.css`
    # - https://example.com/custom.css # remote css
    - css/custom.css

  customJS:
    ## e.g.
    # - js/custom.js # local js in `static/js/custom.js`
    # - https://example.com/custom.js # remote js
